export const siteConfig = {
  name: "Emre Turkan",
  homeTitle: "Emre Turkan — Full Stack Developer in Istanbul",
  alternateNames: ["Emre Türkan", "emreturkan"],
  title: "Emre Turkan - Full Stack Developer | React, Next.js & Node.js",
  description:
    "Full Stack Developer based in Istanbul, Turkey. I build scalable ERP and e-commerce platforms end-to-end with React, Next.js, TypeScript, Node.js and Supabase — including banking, POS, marketplace and shipping API integrations.",
  shortDescription: "Full Stack Developer based in Istanbul, Turkey.",
  url: "https://emreturkan.com",
  ogImage: "https://emreturkan.com/og",
  links: {
    github: "https://github.com/emreturkan",
    linkedin: "https://www.linkedin.com/in/emreturkan/",
    twitter: "https://twitter.com/_emreturkan",
    email: "emreturkan10@gmail.com",
    unsplash: "https://unsplash.com/@emreturkan",
  },
  keywords: [
    "Emre Turkan",
    "Full Stack Developer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "TypeScript Developer",
    "JavaScript Expert",
    "Web Developer Istanbul",
    "Software Engineer Turkey",
    "ERP Developer",
    "Full Stack Engineer",
    "React Expert",
    "Next.js Expert",
    "Tailwind CSS Developer",
    "Full Stack Developer",
    "Web Application Developer",
    "Modern Web Development",
    "Responsive Web Design",
    "Performance Optimization",
    "Istanbul Software Developer",
    "Turkey Tech",
  ],
  creator: "Emre Turkan",
  author: {
    name: "Emre Turkan",
    url: "https://emreturkan.com",
    email: "emreturkan10@gmail.com",
  },
  locale: "en_US",
  alternateLocale: "tr_TR",
  type: "website",
  twitterHandle: "@_emreturkan",
  skills: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Node.js",
    "GraphQL",
    "REST APIs",
    "Git",
    "Figma",
    "Responsive Design",
    "Performance Optimization",
  ],
  experience: {
    company: "EnterERP",
    role: "Full Stack Developer",
    location: "Istanbul, Turkey",
  },
};
