export const siteConfig = {
  name: "Emre Turkan",
  title: "Emre Turkan - Frontend Developer | React & Next.js Expert",
  description:
    "Senior Frontend Developer based in Istanbul, Turkey. Specializing in building high-performance web applications with React, Next.js, and TypeScript. Expert in modern JavaScript, responsive design, and user experience optimization.",
  shortDescription: "Senior Frontend Developer based in Istanbul, Turkey.",
  url: "https://emreturkan.com",
  ogImage: "https://emreturkan.com/og-image.png",
  links: {
    github: "https://github.com/emreturkan",
    linkedin: "https://www.linkedin.com/in/emreturkan/",
    twitter: "https://twitter.com/_emreturkan",
    email: "emreturkan10@gmail.com",
    unsplash: "https://unsplash.com/@emreturkan",
  },
  keywords: [
    "Emre Turkan",
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "JavaScript Expert",
    "Web Developer Istanbul",
    "Software Engineer Turkey",
    "UI Developer",
    "Frontend Engineer",
    "React Expert",
    "Next.js Expert",
    "Tailwind CSS Developer",
    "Full Stack Developer",
    "Web Application Developer",
    "Modern Web Development",
    "Responsive Web Design",
    "Performance Optimization",
    "Istanbul Software Developer",
    "Turkey Tech",
  ],
  creator: "Emre Turkan",
  author: {
    name: "Emre Turkan",
    url: "https://emreturkan.com",
    email: "emreturkan10@gmail.com",
  },
  locale: "en_US",
  alternateLocale: "tr_TR",
  type: "website",
  twitterHandle: "@_emreturkan",
  skills: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Node.js",
    "GraphQL",
    "REST APIs",
    "Git",
    "Figma",
    "Responsive Design",
    "Performance Optimization",
  ],
  experience: {
    company: "EnterERP",
    role: "Frontend Developer",
    location: "Istanbul, Turkey",
  },
};
