export const siteConfig = {
  name: "Emre Turkan",
  title: "Emre Turkan - Frontend Developer",
  description:
    "Frontend Developer based in Istanbul. Passionate about building modern web applications with React, Next.js, and TypeScript. Exploring 3D modeling, photography, FPV drones, and game development with Unity.",
  shortDescription: "Frontend Developer based in Istanbul, Turkey.",
  url: "https://emreturkan.com",
  ogImage: "https://emreturkan.com/og-image.png",
  links: {
    github: "https://github.com/emreturkan",
    linkedin: "https://www.linkedin.com/in/emreturkan/",
    twitter: "https://twitter.com/_emreturkan",
    email: "emreturkan10@gmail.com",
  },
  keywords: [
    "Emre Turkan",
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "JavaScript",
    "Web Developer Istanbul",
    "Software Engineer",
    "UI Developer",
    "Frontend Engineer",
    "React",
    "Next.js",
    "Tailwind CSS",
    "Portfolio",
    "Turkey Developer",
  ],
  creator: "Emre Turkan",
  author: {
    name: "Emre Turkan",
    url: "https://emreturkan.com",
    email: "emreturkan10@gmail.com",
  },
  locale: "en_US",
  type: "website",
};
